// *****************************************************************************
// File generated by STM32 Imager 1.0
// Image name : background
// Coding : 16bpp mode RGB565
// Source file : C:\Users\mrsuyyagh\Desktop\LCD Examples\background.bmp
// *****************************************************************************

#define background_height 320
#define background_width 240
#define background_bpp 4

